/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEyecareRouteImport } from './routes/admin.eyecare'
import { Route as AssessmentTypeRouteImport } from './routes/assessment.$type'
import { Route as ConsultancyIndexRouteImport } from './routes/consultancy.index'
import { Route as ConsultancyEyeCareRouteImport } from './routes/consultancy.eye-care'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEyecareRoute = AdminEyecareRouteImport.update({
  id: '/admin/eyecare',
  path: '/admin/eyecare',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentTypeRoute = AssessmentTypeRouteImport.update({
  id: '/assessment/$type',
  path: '/assessment/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultancyIndexRoute = ConsultancyIndexRouteImport.update({
  id: '/consultancy/',
  path: '/consultancy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultancyEyeCareRoute = ConsultancyEyeCareRouteImport.update({
  id: '/consultancy/eye-care',
  path: '/consultancy/eye-care',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/eyecare': typeof AdminEyecareRoute
  '/assessment/$type': typeof AssessmentTypeRoute
  '/consultancy/eye-care': typeof ConsultancyEyeCareRoute
  '/admin/': typeof AdminIndexRoute
  '/consultancy/': typeof ConsultancyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/eyecare': typeof AdminEyecareRoute
  '/assessment/$type': typeof AssessmentTypeRoute
  '/consultancy/eye-care': typeof ConsultancyEyeCareRoute
  '/admin': typeof AdminIndexRoute
  '/consultancy': typeof ConsultancyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/eyecare': typeof AdminEyecareRoute
  '/assessment/$type': typeof AssessmentTypeRoute
  '/consultancy/eye-care': typeof ConsultancyEyeCareRoute
  '/admin/': typeof AdminIndexRoute
  '/consultancy/': typeof ConsultancyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/eyecare'
    | '/assessment/$type'
    | '/consultancy/eye-care'
    | '/admin/'
    | '/consultancy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/eyecare'
    | '/assessment/$type'
    | '/consultancy/eye-care'
    | '/admin'
    | '/consultancy'
  id:
    | '__root__'
    | '/'
    | '/admin/eyecare'
    | '/assessment/$type'
    | '/consultancy/eye-care'
    | '/admin/'
    | '/consultancy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminEyecareRoute: typeof AdminEyecareRoute
  AssessmentTypeRoute: typeof AssessmentTypeRoute
  ConsultancyEyeCareRoute: typeof ConsultancyEyeCareRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ConsultancyIndexRoute: typeof ConsultancyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eyecare': {
      id: '/admin/eyecare'
      path: '/admin/eyecare'
      fullPath: '/admin/eyecare'
      preLoaderRoute: typeof AdminEyecareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$type': {
      id: '/assessment/$type'
      path: '/assessment/$type'
      fullPath: '/assessment/$type'
      preLoaderRoute: typeof AssessmentTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultancy/': {
      id: '/consultancy/'
      path: '/consultancy'
      fullPath: '/consultancy/'
      preLoaderRoute: typeof ConsultancyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultancy/eye-care': {
      id: '/consultancy/eye-care'
      path: '/consultancy/eye-care'
      fullPath: '/consultancy/eye-care'
      preLoaderRoute: typeof ConsultancyEyeCareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminEyecareRoute: AdminEyecareRoute,
  AssessmentTypeRoute: AssessmentTypeRoute,
  ConsultancyEyeCareRoute: ConsultancyEyeCareRoute,
  AdminIndexRoute: AdminIndexRoute,
  ConsultancyIndexRoute: ConsultancyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
